name: Build and Publish libphonenumber

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip

      - name: Get latest libphonenumber release
        id: get_release
        run: |
          latest=$(curl -s https://api.github.com/repos/google/libphonenumber/releases/latest | jq -r .tag_name)
          echo "latest_tag=$latest" >> $GITHUB_OUTPUT

      - name: Download and verify Closure Compiler
        run: |
          CLOSURE_VERSION="v20250402"
          CLOSURE_URL="https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/${CLOSURE_VERSION}/closure-compiler-${CLOSURE_VERSION}.jar"
          
          echo "Downloading Closure Compiler from ${CLOSURE_URL}"
          
          # Create a temporary directory for downloads
          mkdir -p tmp
          cd tmp
          
          # Download with curl and follow redirects
          if ! curl -L -o closure-compiler.jar "${CLOSURE_URL}"; then
            echo "Failed to download Closure Compiler"
            exit 1
          fi
          
          # Robust JAR check
          if ! unzip -tq closure-compiler.jar > /dev/null; then
            echo "Downloaded file is not a valid JAR file"
            exit 1
          fi
          
          # Move to parent directory if verification passed
          mv closure-compiler.jar ../
          cd ..
          rm -rf tmp
          
          # Final verification
          if ! java -jar closure-compiler.jar --version; then
            echo "Closure Compiler verification failed"
            exit 1
          fi
          
          echo "Closure Compiler downloaded and verified successfully"

      - name: Clone libphonenumber and closure-library
        run: |
          git clone --depth 1 --branch ${{ steps.get_release.outputs.latest_tag }} https://github.com/google/libphonenumber.git
          git clone --depth 1 https://github.com/google/closure-library.git

      - name: Create build directories
        run: |
          mkdir -p dist
          mkdir -p package/dist

      - name: Run Closure Compiler
        run: |
          # List all required source files explicitly
          SOURCES=(
            "$(pwd)/libphonenumber/javascript/i18n/phonenumbers/phonenumberutil.js"
            "$(pwd)/libphonenumber/javascript/i18n/phonenumbers/metadata.js"
            "$(pwd)/libphonenumber/javascript/i18n/phonenumbers/phonenumber.pb.js"
            "$(pwd)/libphonenumber/javascript/i18n/phonenumbers/asyoutypeformatter.js"
            "$(pwd)/libphonenumber/javascript/i18n/phonenumbers/phonemetadata.pb.js"
          )
          
          # Convert array to space-separated string with --js prefix
          JS_FILES=$(printf -- '--js=%s ' "${SOURCES[@]}")
          
          java -jar closure-compiler.jar \
            ${JS_FILES} \
            --
